### PR TITLE
fix: add external table grant to snowflake_grant_privileges_to_role resource

### LINKED ISSUE #1952: external_table_grant deprecated, but doesn't have support in snowflake_grant_privileges_to_role
**Provider Version**

0.68.1

**Terraform Version**

1.0.8

**Describe the bug**

This pull requested deprecated the ExternalTableGrant: https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/1929/files#diff-c7dc3edb296af39a8681c412f574df7fb6e74e357cfb135a27f23cc6096df462

However, based on the updated docs in this pull request, there is no support for External Tables with `snowflake_grant_privileges_to_role`: https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/1941

**Expected behavior**

External Tables should be supported in `snowflake_grant_privileges_to_role`

### PR DESCRIPTION
**Pull request by sfc-gh-swinkler**
fixes #1952

### CODE REVIEW

File: pkg/sdk/object_types.go [hunk 1]
```diff
@@ -111,24 +156,48 @@ func (o ObjectType) GetObjectIdentifier(fullyQualifiedName string) ObjectIdentif
...
-	PluralObjectTypeRoles              PluralObjectType = "ROLES"
-	PluralObjectTypeSchemas            PluralObjectType = "SCHEMAS"
-	PluralObjectTypeSessionPolicies    PluralObjectType = "SESSION POLICIES"
-	PluralObjectTypeShares             PluralObjectType = "SHARES"
-	PluralObjectTypeTables             PluralObjectType = "TABLES"
-	PluralObjectTypeTags               PluralObjectType = "TAGS"
-	PluralObjectTypeTasks              PluralObjectType = "TASKS"
-	PluralObjectTypeUsers              PluralObjectType = "USERS"
-	PluralObjectTypeWarehouses         PluralObjectType = "WAREHOUSES"
+	PluralObjectTypeAccounts            = "ACCOUNTS"
```
Comment (sfc-gh-pbosak) [inline pkg/sdk/object_types.go:159]: maybe add the type signature to the constants?

**Review by sfc-gh-ngaberel — APPROVED** [review]
