### PR TITLE
fix: Adds case statement for ObjectTypeUser in ShowObjectParameter.

### LINKED ISSUE #2669: snowflake_object_parameter parsing error
### Terraform CLI and Provider Versions

```
 .\terraform.exe version
Terraform v1.7.3rsi_versi_
on windows_amd64
+ provider registry.terraform.io/snowflake-labs/snowflake v0.87.2

Your version of Terraform is out of date! The latest version
is 1.7.5. You can update by downloading from https://www.terraform.io/downloads.html
```

### Terraform Configuration

```terraform
resource "snowflake_object_parameter" "AYOU_UNREDACTED_QUERIES" {
  key   = "ENABLE_UNREDACTED_QUERY_SYNTAX_ERROR"
  value = true

  object_type = "User"
  object_identifier {
    name = "USERNAME@EMAIL.COM"
  }
}
```

### Expected Behavior

Applies the query ```
ALTER User "USERNAME@EMAIL.COM" SET ENABLE_UNREDACTED_QUERY_SYNTAX_ERROR = true ```

### Actual Behavior

Improperly parses the email address used for the user causing the command to fail. 
``` ALTER User "USERNAME@EMAIL"."COM" SET ENABLE_UNREDACTED_QUERY_SYNTAX_ERROR = true```

### Steps to Reproduce

1. Create a user with an email address as the identifier
2. assign above paramaeter to just that user using it's emial address
3. Terraform apply will read it correctly, but when you confrm the change the sql command sent to snowflake breaks up the email address as if the period was identifying database sub object

### How much impact is this issue causing?

Medium

### Logs

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by cmonty-paypal**
When issuing `object_type = "USER"` via the `snowflake_object_parameter` resource  the `ShowObjectParameter` function did not handle the `ObjectTypeUser` which led to invalid ObjectType errors.

## Test Plan
* [x] acceptance tests

## References
* ~~Fixes #2669~~ Actually, I re-reading this issue I don't think it fixes this error.

### CODE REVIEW

File: pkg/acceptance/testing.go [hunk 1]
```diff
@@ -24,6 +24,7 @@ const (
 	TestSchemaName     = "terraform_test_schema"
 	TestWarehouseName  = "terraform_test_warehouse"
 	TestWarehouseName2 = "terraform_test_warehouse_2"
+	TestUserName       = "terraform_test_user"
```
Comment (sfc-gh-asawicki) [inline pkg/acceptance/testing.go:27]: Please do not create the user in this global setup but create one in PreConfig or by simply adding `resource snowflake_user test_user {...}` to the config used in the test.

**Review by sfc-gh-jcieslak — DISMISSED** [review]
Hey, looks good. Thank you for the contribution :)

**Review by sfc-gh-asawicki — CHANGES_REQUESTED** [review]
I like the change, only one small comment left.

**Comment by cmonty-paypal** [comment]
> I like the change, only one small comment left.

Thanks for the feedback, I refactored the test user.

**Review by sfc-gh-asawicki — APPROVED** [review]

**Comment by sfc-gh-asawicki** [comment]
Merged. Thanks for the contribution @cmonty-paypal! 🎉
