### PR TITLE
fix: Fix small issues

### LINKED ISSUE #2167: Plugin crashes when upating `snowflake_resource_monitor`
**Provider Version**

`v0.72.0`

**Terraform Version**

`1.6.2`

**Describe the bug**

When trying to add a new user to `snowflake_resource_monitor` it crashes.

**Expected behavior**

It should update the resource monitor with the additional user

**Code samples and commands**

The error occured when adding `User2` to `notify_users`

```
resource "snowflake_resource_monitor" "demo" {
  name         = snowflake_warehouse.demo.name
  credit_quota = 5

  frequency       = "DAILY"
  start_timestamp = "2023-11-01T17:00:00-07:00"
  end_timestamp   = "2024-10-31T17:00:00-07:00"

  notify_triggers           = [75]
  suspend_trigger           = 85
  suspend_immediate_trigger = 95

  notify_users = ["User1", "User2"]
  warehouses   = [snowflake_warehouse.demo.name]
}
```

**Additional context**

```
snowflake_resource_monitor.demo: Modifying... [id=DEMO_WH]
╷
│ Error: Request cancelled
│
│   with snowflake_resource_monitor.demo,
│   on demo.tf line 7, in resource "snowflake_resource_monitor" "demo":
│    7: resource "snowflake_resource_monitor" "demo" {
│
│ The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
╵

Stack trace from the terraform-provider-snowflake_v0.72.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x8 pc=0x103669608]

goroutine 16 [running]:
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.UpdateResourceMonitor(0x14000f38300, {0x103f6a760?, 0x14000b0e340?})
	github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/resource_monitor.go:346 +0x1448
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0x103fa88c0?, {0x103fa88c0?, 0x14000f2e870?}, 0xd?, {0x103f6a760?, 0x14000b0e340?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:800 +0x134
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x1400061fb20, {0x103fa88c0, 0x14000f2e870}, 0x14000ef5040, 0x14000f38180, {0x103f6a760, 0x14000b0e340})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:919 +0x6b0
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x14000c92018, {0x103fa88c0?, 0x14000f2e750?}, 0x14000f14820)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/grpc_provider.go:1060 +0xb78
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x14000c9c000, {0x103fa88c0?, 0x14000f03d40?}, 0x14000edb0a0)
	github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/tf5server/server.go:859 +0x3bc
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x103f1dca0?, 0x14000c9c000}, {0x103fa88c0, 0x14000f03d40}, 0x14000edb030, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:467 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0x14000780d20, {0x103fb7e20, 0x14000c0cb60}, 0x14000e41560, 0x14000c8a180, 0x104b64c78, 0x0)
	google.golang.org/grpc@v1.57.0/server.go:1360 +0xcb4
google.golang.org/grpc.(*Server).handleStream(0x14000780d20, {0x103fb7e20, 0x14000c0cb60}, 0x14000e41560, 0x0)
	google.golang.org/grpc@v1.57.0/server.go:1737 +0x82c
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	google.golang.org/grpc@v1.57.0/server.go:982 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.57.0/server.go:980 +0x16c

Error: The terraform-provider-snowflake_v0.72.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### LINKED ISSUE #2175: Error: The terraform-provider-snowflake_v0.72.0 plugin crashed!
**Provider Version**

v0.72.0

**Terraform Version**

Will update later.

**Describe the bug**

Terraform Snowflake plugin crashed when I tried to add another user to email recipient list of resource monitors during terraform apply.

**Expected behavior**

No error. 

**Code samples and commands**

terragrunt apply tf.plan

**Additional context**

Error screenshot:
image

### LINKED ISSUE #2276: Dynamic Table does not update query on change
### Terraform CLI and Provider Versions

Terraform: 1.3.9
Snowflake provider: 0.76.0

### Terraform Configuration

```terraform
snowflake = {
  source  = "Snowflake-Labs/snowflake"
  version = "~> 0.76.0"
}

resource "snowflake_dynamic_table" "dynamic" {
  name     = var.TABLE_NAME
  database = var.DATABASE_NAME
  schema   = var.SCHEMA_NAME

  warehouse = "WAREHOUSE"

  target_lag {
    maximum_duration = "9 minutes"
  }

  query     = templatefile("${path.module}/dynamic_table.sql.tmpl", {
    DATABASE_NAME = var.DATABASE_NAME,
    SCHEMA_NAME   = var.SCHEMA_NAME,
    TABLE_NAME    = var.TABLE_NAME
  })
}
```

### Expected Behavior

When updating the SQL template file I expect the dynamic table to change as well after applying.

### Actual Behavior

When planning changes, terraform detects a change in the SQL templatefile and provides those changes visually before approving. Nonetheless it does not update inside snowflake. The only way it is "updated" is to rename the resource so that TF deletes the old version and creates a new one with the right script...

### Steps to Reproduce

1. Create template file with legit SQL
2. `terraform apply`
3. Change template file
4. 'terraform apply' again

### How much impact is this issue causing?

High

### Logs

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by sfc-gh-asawicki**
- Fix resource monitor update
- Handle dynamic table's query update

Fix #2167 
Fix #2276 
Fix #2175

### CODE REVIEW

File: pkg/resources/dynamic_table_acceptance_test.go [hunk 1]
```diff
@@ -236,6 +236,54 @@ func TestAcc_DynamicTable_issue2134(t *testing.T) {
...
+			tfversion.RequireAbove(tfversion.Version1_5_0),
+		},
+		CheckDestroy: testAccCheckDynamicTableDestroy,
+		Steps: []resource.TestStep{
+			{
+				ConfigDirectory: config.TestStepDirectory(),
+				ConfigVariables: m(),
+				Check: resource.ComposeTestCheckFunc(
+					resource.TestCheckResourceAttr("snowflake_dynamic_table.dt", "name", dynamicTableName),
+					resource.TestCheckResourceAttr("snowflake_dynamic_table.dt", "query", fmt.Sprintf("select \"id\" from \"%v\".\"%v\".\"%v\"", acc.TestDatabaseName, acc.TestSchemaName, tableName)),
```
Comment (sfc-gh-jcieslak) [inline pkg/resources/dynamic_table_acceptance_test.go:272]: you can just use query and newQuery variables

**Review by sfc-gh-jcieslak — APPROVED** [review]

**Review by scottwinkler — APPROVED** [review]
