### PR TITLE
fix: schema name is optional for future snowflake_stage_grant

### LINKED ISSUE #1100: In snowflake_stage_grant with on_future=on it is required to provide schema_name
**Provider Version**

0.37.1

**Terraform Version**

1.2.3

**Describe the bug**

in snowflake_stage_grants when you chose **_"on_future= true"_** it is required to provide schema_name, but in parameter description you said that it is optional

https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/stage_grant#schema_name

image

**Expected behavior**

in snowflake_stage_grant if you choose on_future=true, it could be created without providing schema_name

**Code samples and commands**

image

### LINKED ISSUE #1477: [snowflake_stage_grant] schema_name is not required
**Provider Version**

0.54.0

**Terraform Version**

1.2.6

**Describe the bug**

When using snowflake_stage_grant with the `on_future` falg as `true` the `schema_name` is being required

**Expected behavior**

As per the documentation:

>  When this is true and no schema_name is provided apply this grant on all future stages in the given database. 

**Code samples and commands**

```
module "snowflake_on_future_read_only_stages" {
  source = "resource_module"

  database_name     = "DATABASE"
  privilege         = "USAGE"
  roles             = ["ROLE"]
  on_future         = true
  with_grant_option = false
}

```

Error:

> The argument "schema_name" is required, but no definition was found.

**Additional context**

### PR DESCRIPTION
**Pull request by bennylu2**
Closes #1100 
Closes #1477 

```
make test
CGO_ENABLED=1 go test -race -coverprofile=coverage.txt -covermode=atomic  ./...
?       github.com/Snowflake-Labs/terraform-provider-snowflake  [no test files]
ok      github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/datasources  2.843s  coverage: 3.6% of statements
?       github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/db   [no test files]
?       github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/helpers      [no test files]
ok      github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/provider     4.256s  coverage: 25.5% of statements
ok      github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources    13.904s coverage: 46.9% of statements
ok      github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/snowflake    0.676s  coverage: 46.8% of statements
?       github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/testhelpers  [no test files]
ok      github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/validation   0.439s  coverage: 31.8% of statements
?       github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/version      [no test files]
```

### CODE REVIEW

File: pkg/resources/stage_grant.go [hunk 1]
```diff
@@ -92,18 +94,32 @@ func StageGrant() *TerraformGrantResource {
...
+	if (stageName == "") && !onFuture {
+		return errors.New("stage_name must be set unless on_future is true")
+	}
+
 	var builder snowflake.GrantBuilder
-	if futureStages {
+	if onFuture {
 		builder = snowflake.FutureStageGrant(dbName, schemaName)
 	} else {
 		builder = snowflake.StageGrant(dbName, schemaName, stageName)
```
Comment (bennylu2) [inline pkg/resources/stage_grant.go:125]: When setting grant, should we be passing roles to generate a unique grant id? I think that would be a breaking change if we added tho
