### PR TITLE
fix: file format now supports reading options

### LINKED ISSUE #1706: Snowflake File Format defaults not retained by subsequent Terraform Plans
**Provider Version**

version = "= 0.61.0"

**Terraform Version**

required_version = "= 1.3.6"

**Describe the bug**

Snowflake File Format resource created successfully. Subsequent plans attempt to unset default values to null causing deployment failures when applied

**Expected behavior**

Terraform plan picks up no changes where none's been made

**Code samples and commands**

Resource created successfully - 

resource "snowflake_file_format" "csv_format" {
  name                           = "CSV_FORMAT"
  database                     = snowflake_database.db.name
  schema                       = snowflake_schema.schema.name
  format_type                = "CSV"
  skip_header                  = 1
  field_optionally_enclosed_by = "0x22"
}

Terraform plan change (attempts to reset the defaults)

# snowflake_file_format.data_raw_dialler_csv_format will be updated in-place
  ~ resource "snowflake_file_format" "csv_format" {
      - binary_format                  = "HEX" -> null
      - compression                    = "AUTO" -> null
      - date_format                    = "AUTO" -> null
      - encoding                       = "UTF8" -> null
      - escape                         = "NONE" -> null
      - escape_unenclosed_field        = "\\" -> null
      - field_delimiter                = "," -> null
      ~ field_optionally_enclosed_by   = "\"" -> "0x22"
        id                             = "DATA_RAW|RAW_DIALLER|CSV_FORMAT"
        name                           = "CSV_FORMAT"
      - record_delimiter               = <<-EOT
            
        EOT -> null
      - time_format                    = "AUTO" -> null
      - timestamp_format               = "AUTO" -> null
        # (21 unchanged attributes hidden)
    }

Error during Terraform Apply

Error: -05T16:35:54.472Z [ERROR] provider.terraform-provider-snowflake_v0.56.3: Response contains error diagnostic: @caller=github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/internal/diag/diagnostics.go:55 diagnostic_detail= diagnostic_severity=ERROR tf_proto_version=5.3 tf_provider_addr=registry.terraform.io/Snowflake-Labs/snowflake tf_req_id=aaed465c-02a2-c7f2-7f41-048ef2480d02 tf_resource_type=snowflake_file_format tf_rpc=ApplyResourceChange @module=sdk.proto diagnostic_summary="error updating file format compression on DATA_RAW|RAW_DIALLER|CSV_FORMAT err = 001008 (22023): SQL compilation error:
invalid value [''] for parameter 'COMPRESSION'" timestamp=2023-04-05T16:35:54.472Z
Error: -05T16:35:54.482Z [ERROR] vertex "snowflake_file_format.data_raw_dialler_csv_format" error: error updating file format compression on DATA_RAW|RAW_DIALLER|CSV_FORMAT err = 001008 (22023): SQL compilation error:
invalid value [''] for parameter 'COMPRESSION'

**Additional context**

Appears to be a plugin issue. We tried some earlier versions of the plugin only to observe the same behaviour.

I have removed the actual db and schema names for obvious reasons

### PR DESCRIPTION
**Pull request by sfc-gh-ngaberel**
Migrate file format resource and datasource to new sdk with support for reading options.

## Test Plan
* [X] New unit and integration tests in SDK
* [X] Kept and improved existing acceptance tests

## References
Fixes #1706

### CODE REVIEW

File: pkg/sdk/file_format_test.go [hunk 1]
```diff
@@ -0,0 +1,316 @@
...
+				CsvTimeFormat:                String("HH:mm:SS"),
+				CsvTimestampFormat:           String("time"),
+				CsvBinaryFormat:              &BinaryFormatUtf8,
+				CsvEscape:                    String("\\"),
+				CsvEscapeUnenclosedField:     String("§"),
+				CsvTrimSpace:                 Bool(true),
+				CsvFieldOptionallyEnclosedBy: String("&"),
+				CsvNullIf: &[]NullString{
+					{"nul"},
+					{"nulll"},
```
Comment (sfc-gh-swinkler) [inline pkg/sdk/file_format_test.go:48]: is 3 l's okay?

File: pkg/sdk/sql_builder.go [hunk 2]
```diff
@@ -58,10 +74,10 @@ func (qm quoteModifier) Modify(v any) string {
 		escapedString := strings.ReplaceAll(s, qm.String(), qm.String()+qm.String())
 		return fmt.Sprintf(`%v%v%v`, qm.String(), escapedString, qm.String())
 	case SingleQuotes:
-		// https://docs.snowflake.com/en/sql-reference/data-types-text#single-quoted-string-constants
-		// replace all single quotes with \'
-		escapedString := strings.ReplaceAll(s, qm.String(), `\'`)
-		return fmt.Sprintf(`%v%v%v`, qm.String(), escapedString, qm.String())
+		for _, pair := range singleQuoteEscapes {
```
Comment (sfc-gh-swinkler) [inline pkg/sdk/sql_builder.go:77]: glad that we finally have a good solution to this

File: pkg/resources/file_format.go [hunk 3]
```diff
@@ -146,31 +148,37 @@ var fileFormatSchema = map[string]*schema.Schema{
 	"date_format": {
 		Type:        schema.TypeString,
 		Optional:    true,
+		Computed:    true,
```
Comment (sfc-gh-swinkler) [inline pkg/resources/file_format.go:151]: should this be computed? my understanding is that computed attributes should be read-only. Perhaps adding a default of "AUTO" would make more sense?

File: pkg/sdk/file_format.go [hunk 4]
```diff
@@ -0,0 +1,1038 @@
...
+}
+
+type FileFormat struct {
+	Name          SchemaObjectIdentifier
+	CreatedOn     time.Time
+	Type          FileFormatType
+	Owner         string
+	Comment       string
+	OwnerRoleType string
+	Options       FileFormatTypeOptions
```
[the remark this answers is not in the document]
Comment (sfc-gh-ngaberel) [reply pkg/sdk/file_format.go:42]: Sounds a bit redundant considering it's a field in a type named `FileFormat`. I can rename if you feel strongly about it.

File: pkg/sdk/file_format.go [hunk 5]
```diff
@@ -0,0 +1,1038 @@
...
+	XmlCompressionGzip       XmlCompression = "GZIP"
+	XmlCompressionBz2        XmlCompression = "BZ2"
+	XmlCompressionBrotli     XmlCompression = "BROTLI"
+	XmlCompressionZstd       XmlCompression = "ZSTD"
+	XmlCompressionDeflate    XmlCompression = "DEFLATE"
+	XmlCompressionRawDeflate XmlCompression = "RAW_DEFLATE"
+	XmlCompressionNone       XmlCompression = "NONE"
+)
+
+type NullString struct {
```
[the remark this answers is not in the document]
Comment (sfc-gh-ngaberel) [reply pkg/sdk/file_format.go:316]: No it's only meant to hold strings to be used in the NULL_IF parameters (https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/1917/files#diff-7e89fb0973fe2d7e7a859868ae043401a033d6e4af4a3b0a3d8edbce43c2af44R412). I couldn't find an better way to allow passing a list of strings, maybe there's a better way to implement this with the sql builder?

File: pkg/sdk/file_format.go [hunk 6]
```diff
@@ -0,0 +1,1038 @@
...
+type CreateFileFormatOptions struct {
+	create      bool                   `ddl:"static" sql:"CREATE"` //lint:ignore U1000 This is used in the ddl tag
+	OrReplace   *bool                  `ddl:"keyword" sql:"OR REPLACE"`
+	Temporary   *bool                  `ddl:"keyword" sql:"TEMPORARY"`
+	fileFormat  bool                   `ddl:"static" sql:"FILE FORMAT"` //lint:ignore U1000 This is used in the ddl tag
+	IfNotExists *bool                  `ddl:"keyword" sql:"IF NOT EXISTS"`
+	name        SchemaObjectIdentifier `ddl:"identifier"`
+	Type        FileFormatType         `ddl:"parameter" sql:"TYPE"`
+
+	FileFormatTypeOptions
```
[the remark this answers is not in the document]
Comment (sfc-gh-ngaberel) [reply pkg/sdk/file_format.go:329]: I didn't even need to modify the sql builder but I can add it.

File: pkg/sdk/file_format.go [hunk 7]
```diff
@@ -0,0 +1,1038 @@
...
+	return err
+}
+
+type AlterFileFormatOptions struct {
+	alter      bool                   `ddl:"static" sql:"ALTER"`       //lint:ignore U1000 This is used in the ddl tag
+	fileFormat bool                   `ddl:"static" sql:"FILE FORMAT"` //lint:ignore U1000 This is used in the ddl tag
+	IfExists   *bool                  `ddl:"keyword" sql:"IF EXISTS"`
+	name       SchemaObjectIdentifier `ddl:"identifier"`
+
+	Rename *AlterFileFormatRenameOptions
```
[the remark this answers is not in the document]
Comment (sfc-gh-ngaberel) [reply pkg/sdk/file_format.go:374]: I found examples of both names in the code base, I think I've been using Rename and you've been using NewName. Happy to go with either, I went with Rename because it's closed to the sql.

File: pkg/sdk/file_format_test.go (hunk 1 above)
Comment (sfc-gh-ngaberel) [reply pkg/sdk/file_format_test.go:48]: yes the actual value doesn't matter, as long as it matches below. Users are meant to specify any special value they use for null.

File: pkg/resources/file_format.go (hunk 3 above)
Comment (sfc-gh-ngaberel) [reply pkg/resources/file_format.go:151]: Yes that was my assumption too but then I found [this stack overflow answer](https://stackoverflow.com/questions/57784666/how-should-a-terraform-provider-handle-default-values-applied-on-the-server-side). Turns out using optional + computed allows us to set a default value when it is not set by the user. 
- using optional alone means we can't set a default value without generating drift (tf expects a null value but Read returns something)
- using computed alone does not allow the user to set a value

Comment (sfc-gh-swinkler) [reply pkg/resources/file_format.go:151]: noted

**Review by sfc-gh-swinkler — APPROVED** [review]
